package main

import (
	"syscall"
)

// DLLها و پروکجرهای Win32 API
var (
	user32   = syscall.NewLazyDLL("user32.dll")
	kernel32 = syscall.NewLazyDLL("kernel32.dll")
	gdi32    = syscall.NewLazyDLL("gdi32.dll")
	advapi32 = syscall.NewLazyDLL("advapi32.dll")
	xinput   = syscall.NewLazyDLL("xinput1_4.dll")
	dwmapi   = syscall.NewLazyDLL("dwmapi.dll")

	procGetMessage            = user32.NewProc("GetMessageW")
	procTranslateMsg          = user32.NewProc("TranslateMessage")
	procDispatchMsg           = user32.NewProc("DispatchMessageW")
	procCreateWindow          = user32.NewProc("CreateWindowExW")
	procDefWindowProc         = user32.NewProc("DefWindowProcW")
	procRegisterClassEx       = user32.NewProc("RegisterClassExW")
	procLoadCursor            = user32.NewProc("LoadCursorW")
	procLoadImage             = user32.NewProc("LoadImageW")
	procBeginPaint            = user32.NewProc("BeginPaint")
	procEndPaint              = user32.NewProc("EndPaint")
	procGetClientRect         = user32.NewProc("GetClientRect")
	procDrawText              = user32.NewProc("DrawTextW")
	procInvalidateRect        = user32.NewProc("InvalidateRect")
	procMessageBox            = user32.NewProc("MessageBoxW")
	procShowWindow            = user32.NewProc("ShowWindow")
	procSetTimer              = user32.NewProc("SetTimer")
	procSendMessage           = user32.NewProc("SendMessageW")
	procSetLayeredWindowAttr  = user32.NewProc("SetLayeredWindowAttributes")
	procDwmSetWindowAttribute = dwmapi.NewProc("DwmSetWindowAttribute")

	procGetModuleHandle      = kernel32.NewProc("GetModuleHandleW")
	procGetSystemPowerStatus = kernel32.NewProc("GetSystemPowerStatus")
	procBeep                 = kernel32.NewProc("Beep")
	procGlobalMemoryStatus   = kernel32.NewProc("GlobalMemoryStatusEx")
	procGetDiskFreeSpace     = kernel32.NewProc("GetDiskFreeSpaceExW")
	procGetSystemTimes       = kernel32.NewProc("GetSystemTimes")
	procXInputGetState       = xinput.NewProc("XInputGetState")
	procOpenSCManager        = advapi32.NewProc("OpenSCManagerW")
	procOpenService          = advapi32.NewProc("OpenServiceW")
	procQueryServiceStatus   = advapi32.NewProc("QueryServiceStatus")
	procCloseServiceHandle   = advapi32.NewProc("CloseServiceHandle")

	procCreateSolidBrush = gdi32.NewProc("CreateSolidBrush")
	procSelectObject     = gdi32.NewProc("SelectObject")
	procDeleteObject     = gdi32.NewProc("DeleteObject")
	procEllipse          = gdi32.NewProc("Ellipse")
	procRoundRect        = gdi32.NewProc("RoundRect")
	procRectangle        = gdi32.NewProc("Rectangle")
	procSetTextColor     = gdi32.NewProc("SetTextColor")
	procSetBkMode        = gdi32.NewProc("SetBkMode")
	procCreateFontW      = gdi32.NewProc("CreateFontW")

	procCreatePen = gdi32.NewProc("CreatePen")
	procMoveToEx  = gdi32.NewProc("MoveToEx")
	procLineTo    = gdi32.NewProc("LineTo")
	procPolygon   = gdi32.NewProc("Polygon")
)
